import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - HomeIdeasAI",
  description:
    "HomeIdeasAI's terms of service outline the rules and regulations for using our website and services.",
};

export default function TermsOfServicePage() {
  return (
    <div className="container mx-auto px-4 pt-20 pb-12 max-w-4xl">
      <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
        <p>
          By accessing or using HomeIdeasAI's website and services, you agree to
          be bound by these Terms of Service. If you do not agree to these
          terms, please do not use our services.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">
          2. Description of Service
        </h2>
        <p>
          HomeIdeasAI provides an AI-powered home design generation tool. Our
          service allows users to create and visualize nail art designs using
          artificial intelligence technology.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">3. User Accounts</h2>
        <p>
          To access certain features of our service, you may be required to
          create an account. You are responsible for maintaining the
          confidentiality of your account information and for all activities
          that occur under your account.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">
          4. Intellectual Property Rights
        </h2>
        <p>
          The designs generated by HomeIdeasAI are for personal use only. You
          may not claim ownership of the AI-generated designs or use them for
          commercial purposes without explicit permission from HomeIdeasAI.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">5. User Content</h2>
        <p>
          By submitting content to our service (such as design preferences or
          feedback), you grant HomeIdeasAI a worldwide, non-exclusive,
          royalty-free license to use, reproduce, and display the content in
          connection with our service.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">
          6. Limitation of Liability
        </h2>
        <p>
          HomeIdeasAI is not liable for any indirect, incidental, special,
          consequential, or punitive damages resulting from your use of our
          services or any content provided by our services.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">7. Changes to Terms</h2>
        <p>
          We reserve the right to modify these Terms of Service at any time. We
          will notify users of any significant changes by posting a notice on
          our website.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-4">8. Contact Us</h2>
        <p>
          If you have any questions about these Terms of Service, please contact
          us at legal@homeideasai.com.
        </p>
      </section>

      <p className="mt-8 text-sm text-gray-600">
        Last updated: January 9, 2025
      </p>
    </div>
  );
}
