"""add field

Revision ID: 343856bb7819
Revises: ffd51c20ef34
Create Date: 2024-12-29 14:26:32.338686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '343856bb7819'
down_revision: Union[str, None] = 'ffd51c20ef34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nail_designs', sa.Column('skin_tone_color_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nail_designs', 'skin_tone_color_code')
    # ### end Alembic commands ###
