"""add improved prompt

Revision ID: 78678adcd3ab
Revises: aea58becee37
Create Date: 2025-01-22 15:58:34.997032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '78678adcd3ab'
down_revision: Union[str, None] = 'aea58becee37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nail_try_ons', sa.Column('enhanced_prompt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nail_try_ons', 'enhanced_prompt')
    # ### end Alembic commands ###
