"""add sub stuff

Revision ID: 83e68c690200
Revises: 68eede79aa0c
Create Date: 2025-08-29 01:46:11.141805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '83e68c690200'
down_revision: Union[str, None] = '68eede79aa0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('user', sa.Column('subscription_current_period_start', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('subscription_current_period_end', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('subscription_cancel_at_period_end', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('plan_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'plan_id')
    op.drop_column('user', 'subscription_cancel_at_period_end')
    op.drop_column('user', 'subscription_current_period_end')
    op.drop_column('user', 'subscription_current_period_start')
    op.drop_column('user', 'subscription_status')
    op.drop_column('user', 'stripe_subscription_id')
    # ### end Alembic commands ###
