"""add generations

Revision ID: ffd51c20ef34
Revises: 2c4173865258
Create Date: 2024-12-29 08:35:28.570584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ffd51c20ef34'
down_revision: Union[str, None] = '2c4173865258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nail_designs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skin_tone', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.Column('style', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('technique', sa.String(), nullable=False),
    sa.Column('image_urls', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nail_designs')
    # ### end Alembic commands ###
