// This file is auto-generated by @hey-api/openapi-ts

export type BearerResponse = {
  access_token: string;
  token_type: string;
};

export type Body_auth_reset_forgot_password = {
  email: string;
};

export type Body_auth_reset_reset_password = {
  token: string;
  password: string;
};

export type Body_auth_verify_request_token = {
  email: string;
};

export type Body_auth_verify_verify = {
  token: string;
};

export type Body_billing_create_checkout_session = {
  package_type: string;
  quantity: number;
};

export type Body_nail_try_on_try_on_nail_design = {
  image: Blob | File;
  prompt: string;
  extension_factor?: number;
};

export type CompleteCheckoutSessionResponse = {
  status: string;
  amount: number;
  currency: string;
};

export type ErrorModel = {
  detail:
    | string
    | {
        [key: string]: string;
      };
};

export type ErrorResponse = {
  detail: string;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type InstagramURLRequest = {
  instagram_url: string;
};

export type Invoice = {
  invoice_link: string;
  date: string;
  amount: string;
  credits: number;
};

export type ItemCreate = {
  name: string;
  description?: string | null;
  quantity?: number | null;
};

export type ItemRead = {
  name: string;
  description?: string | null;
  quantity?: number | null;
  id: string;
  user_id: string;
};

export type login = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type NailDesignCreate = {
  skin_tone: string;
  skin_tone_color_code: string;
  description: string;
  color: string;
  shape: string;
  style: string;
  theme: string;
  technique: string;
};

export type NailDesignRead = {
  id: string;
  skin_tone: string;
  skin_tone_color_code: string;
  description: string;
  color: string;
  shape: string;
  style: string;
  theme: string;
  technique: string;
  image_urls: Array<string>;
  created_at: string;
};

export type NailTryOnRead = {
  id: string;
  prompt: string;
  original_image_url: string;
  result_image_url: string;
  created_at: string;
};

export type OAuth2AuthorizeResponse = {
  authorization_url: string;
};

export type StripeCheckoutSession = {
  url: string;
};

export type UserCreate = {
  email: string;
  password: string;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
};

export type UserRead = {
  id: string;
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
  credits?: number | null;
};

export type UserUpdate = {
  password?: string | null;
  email?: string | null;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type AuthJwtLoginData = {
  body: login;
};

export type AuthJwtLoginResponse = BearerResponse;

export type AuthJwtLoginError = ErrorModel | HTTPValidationError;

export type AuthJwtLogoutResponse = unknown;

export type AuthJwtLogoutError = unknown;

export type OauthGoogleJwtAuthorizeData = {
  query?: {
    scopes?: Array<string>;
  };
};

export type OauthGoogleJwtAuthorizeResponse = OAuth2AuthorizeResponse;

export type OauthGoogleJwtAuthorizeError = HTTPValidationError;

export type OauthGoogleJwtCallbackData = {
  query?: {
    code?: string | null;
    code_verifier?: string | null;
    error?: string | null;
    state?: string | null;
  };
};

export type OauthGoogleJwtCallbackResponse = unknown;

export type OauthGoogleJwtCallbackError = ErrorModel | HTTPValidationError;

export type RegisterRegisterData = {
  body: UserCreate;
};

export type RegisterRegisterResponse = UserRead;

export type RegisterRegisterError = ErrorModel | HTTPValidationError;

export type ResetForgotPasswordData = {
  body: Body_auth_reset_forgot_password;
};

export type ResetForgotPasswordResponse = unknown;

export type ResetForgotPasswordError = HTTPValidationError;

export type ResetResetPasswordData = {
  body: Body_auth_reset_reset_password;
};

export type ResetResetPasswordResponse = unknown;

export type ResetResetPasswordError = ErrorModel | HTTPValidationError;

export type VerifyRequestTokenData = {
  body: Body_auth_verify_request_token;
};

export type VerifyRequestTokenResponse = unknown;

export type VerifyRequestTokenError = HTTPValidationError;

export type VerifyVerifyData = {
  body: Body_auth_verify_verify;
};

export type VerifyVerifyResponse = UserRead;

export type VerifyVerifyError = ErrorModel | HTTPValidationError;

export type UsersCurrentUserResponse = UserRead;

export type UsersCurrentUserError = unknown;

export type UsersPatchCurrentUserData = {
  body: UserUpdate;
};

export type UsersPatchCurrentUserResponse = UserRead;

export type UsersPatchCurrentUserError =
  | ErrorModel
  | unknown
  | HTTPValidationError;

export type UsersUserData = {
  path: {
    id: string;
  };
};

export type UsersUserResponse = UserRead;

export type UsersUserError = unknown | HTTPValidationError;

export type UsersPatchUserData = {
  body: UserUpdate;
  path: {
    id: string;
  };
};

export type UsersPatchUserResponse = UserRead;

export type UsersPatchUserError = ErrorModel | unknown | HTTPValidationError;

export type UsersDeleteUserData = {
  path: {
    id: string;
  };
};

export type UsersDeleteUserResponse = void;

export type UsersDeleteUserError = unknown | HTTPValidationError;

export type CreateCheckoutSessionData = {
  body: Body_billing_create_checkout_session;
};

export type CreateCheckoutSessionResponse = StripeCheckoutSession;

export type CreateCheckoutSessionError = HTTPValidationError;

export type StripeWebhookResponse = unknown;

export type StripeWebhookError = unknown;

export type CompleteCheckoutSessionData = {
  body: string;
};

export type CompleteCheckoutSessionResponse2 = CompleteCheckoutSessionResponse;

export type CompleteCheckoutSessionError = HTTPValidationError;

export type GetUserInvoicesResponse = Array<Invoice>;

export type GetUserInvoicesError = unknown;

export type ReadItemResponse = Array<ItemRead>;

export type ReadItemError = unknown;

export type CreateItemData = {
  body: ItemCreate;
};

export type CreateItemResponse = ItemRead;

export type CreateItemError = HTTPValidationError;

export type DeleteItemData = {
  path: {
    item_id: string;
  };
};

export type DeleteItemResponse = unknown;

export type DeleteItemError = HTTPValidationError;

export type AddToWaitlistData = {
  body: string;
};

export type AddToWaitlistResponse = unknown;

export type AddToWaitlistError = HTTPValidationError;

export type TriggerAccountCreatedForAllResponse = unknown;

export type TriggerAccountCreatedForAllError = unknown;

export type GenerateNailDesignsData = {
  body: NailDesignCreate;
};

export type GenerateNailDesignsResponse = NailDesignRead;

export type GenerateNailDesignsError = ErrorResponse | HTTPValidationError;

export type GetUserNailDesignsData = {
  query?: {
    limit?: number;
    skip?: number;
  };
};

export type GetUserNailDesignsResponse = Array<NailDesignRead>;

export type GetUserNailDesignsError = HTTPValidationError;

export type BaserowWebhookResponse = unknown;

export type BaserowWebhookError = unknown;

export type UpdateEmptyNamesInBaserowResponse = unknown;

export type UpdateEmptyNamesInBaserowError = unknown;

export type RemoveDuplicateRowsResponse = unknown;

export type RemoveDuplicateRowsError = unknown;

export type ProcessInstagramUrlData = {
  body: InstagramURLRequest;
};

export type ProcessInstagramUrlResponse = unknown;

export type ProcessInstagramUrlError = HTTPValidationError;

export type TryOnNailDesignData = {
  body: Body_nail_try_on_try_on_nail_design;
};

export type TryOnNailDesignResponse = NailTryOnRead;

export type TryOnNailDesignError = ErrorResponse | HTTPValidationError;

export type GetUserTryOnsData = {
  query?: {
    limit?: number;
    skip?: number;
  };
};

export type GetUserTryOnsResponse = Array<NailTryOnRead>;

export type GetUserTryOnsError = HTTPValidationError;
