// This file is auto-generated by @hey-api/openapi-ts

export type BearerResponse = {
  access_token: string;
  token_type: string;
};

export type Body_auth_reset_forgot_password = {
  email: string;
};

export type Body_auth_reset_reset_password = {
  token: string;
  password: string;
};

export type Body_auth_verify_request_token = {
  email: string;
};

export type Body_auth_verify_verify = {
  token: string;
};

export type Body_billing_create_checkout_session = {
  package_type: string;
  quantity: number;
};

export type Body_home_design_projects_upload_image = {
  file: Blob | File;
};

export type ChatMessage = {
  role: string;
  content: string;
  timestamp?: string | null;
};

export type CompleteCheckoutSessionResponse = {
  status: string;
  amount: number;
  currency: string;
};

export type ErrorModel = {
  detail:
    | string
    | {
        [key: string]: string;
      };
};

export type ErrorResponse = {
  detail: string;
};

export type HomeDesignChatRequest = {
  project_id: string;
  message: string;
  conversation_id?: string | null;
};

export type HomeDesignChatResponse = {
  conversation_id: string;
  message: ChatMessage;
  image_url?: string | null;
};

export type HomeDesignConversationRead = {
  id: string;
  project_id: string;
  messages: Array<{
    [key: string]: unknown;
  }>;
  created_at: string;
  updated_at: string;
};

export type HomeDesignEditRead = {
  id: string;
  project_id: string;
  conversation_id: string | null;
  prompt: string;
  before_image_url: string;
  after_image_url: string;
  edit_type: string;
  created_at: string;
};

export type HomeDesignProjectCreate = {
  name: string;
  description?: string | null;
  original_image_url: string;
  room_type?: string | null;
  style_preference?: string | null;
};

export type HomeDesignProjectRead = {
  id: string;
  name: string;
  description: string | null;
  original_image_url: string;
  current_image_url: string;
  room_type: string | null;
  style_preference: string | null;
  created_at: string;
  updated_at: string;
};

export type HomeDesignProjectUpdate = {
  name?: string | null;
  description?: string | null;
  current_image_url?: string | null;
  room_type?: string | null;
  style_preference?: string | null;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type ImageUploadResponse = {
  image_url: string;
};

export type InstagramURLRequest = {
  instagram_url: string;
};

export type Invoice = {
  invoice_link: string;
  date: string;
  amount: string;
  credits: number;
};

export type ItemCreate = {
  name: string;
  description?: string | null;
  quantity?: number | null;
};

export type ItemRead = {
  name: string;
  description?: string | null;
  quantity?: number | null;
  id: string;
  user_id: string;
};

export type login = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type OAuth2AuthorizeResponse = {
  authorization_url: string;
};

export type StripeCheckoutSession = {
  url: string;
};

export type UserCreate = {
  email: string;
  password: string;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
};

export type UserRead = {
  id: string;
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
  credits?: number | null;
};

export type UserUpdate = {
  password?: string | null;
  email?: string | null;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type AuthJwtLoginData = {
  body: login;
};

export type AuthJwtLoginResponse = BearerResponse;

export type AuthJwtLoginError = ErrorModel | HTTPValidationError;

export type AuthJwtLogoutResponse = unknown;

export type AuthJwtLogoutError = unknown;

export type OauthGoogleJwtAuthorizeData = {
  query?: {
    scopes?: Array<string>;
  };
};

export type OauthGoogleJwtAuthorizeResponse = OAuth2AuthorizeResponse;

export type OauthGoogleJwtAuthorizeError = HTTPValidationError;

export type OauthGoogleJwtCallbackData = {
  query?: {
    code?: string | null;
    code_verifier?: string | null;
    error?: string | null;
    state?: string | null;
  };
};

export type OauthGoogleJwtCallbackResponse = unknown;

export type OauthGoogleJwtCallbackError = ErrorModel | HTTPValidationError;

export type RegisterRegisterData = {
  body: UserCreate;
};

export type RegisterRegisterResponse = UserRead;

export type RegisterRegisterError = ErrorModel | HTTPValidationError;

export type ResetForgotPasswordData = {
  body: Body_auth_reset_forgot_password;
};

export type ResetForgotPasswordResponse = unknown;

export type ResetForgotPasswordError = HTTPValidationError;

export type ResetResetPasswordData = {
  body: Body_auth_reset_reset_password;
};

export type ResetResetPasswordResponse = unknown;

export type ResetResetPasswordError = ErrorModel | HTTPValidationError;

export type VerifyRequestTokenData = {
  body: Body_auth_verify_request_token;
};

export type VerifyRequestTokenResponse = unknown;

export type VerifyRequestTokenError = HTTPValidationError;

export type VerifyVerifyData = {
  body: Body_auth_verify_verify;
};

export type VerifyVerifyResponse = UserRead;

export type VerifyVerifyError = ErrorModel | HTTPValidationError;

export type UsersCurrentUserResponse = UserRead;

export type UsersCurrentUserError = unknown;

export type UsersPatchCurrentUserData = {
  body: UserUpdate;
};

export type UsersPatchCurrentUserResponse = UserRead;

export type UsersPatchCurrentUserError =
  | ErrorModel
  | unknown
  | HTTPValidationError;

export type UsersUserData = {
  path: {
    id: string;
  };
};

export type UsersUserResponse = UserRead;

export type UsersUserError = unknown | HTTPValidationError;

export type UsersPatchUserData = {
  body: UserUpdate;
  path: {
    id: string;
  };
};

export type UsersPatchUserResponse = UserRead;

export type UsersPatchUserError = ErrorModel | unknown | HTTPValidationError;

export type UsersDeleteUserData = {
  path: {
    id: string;
  };
};

export type UsersDeleteUserResponse = void;

export type UsersDeleteUserError = unknown | HTTPValidationError;

export type CreateCheckoutSessionData = {
  body: Body_billing_create_checkout_session;
};

export type CreateCheckoutSessionResponse = StripeCheckoutSession;

export type CreateCheckoutSessionError = HTTPValidationError;

export type StripeWebhookResponse = unknown;

export type StripeWebhookError = unknown;

export type CompleteCheckoutSessionData = {
  body: string;
};

export type CompleteCheckoutSessionResponse2 = CompleteCheckoutSessionResponse;

export type CompleteCheckoutSessionError = HTTPValidationError;

export type GetUserInvoicesResponse = Array<Invoice>;

export type GetUserInvoicesError = unknown;

export type ReadItemResponse = Array<ItemRead>;

export type ReadItemError = unknown;

export type CreateItemData = {
  body: ItemCreate;
};

export type CreateItemResponse = ItemRead;

export type CreateItemError = HTTPValidationError;

export type DeleteItemData = {
  path: {
    item_id: string;
  };
};

export type DeleteItemResponse = unknown;

export type DeleteItemError = HTTPValidationError;

export type AddToWaitlistData = {
  body: string;
};

export type AddToWaitlistResponse = unknown;

export type AddToWaitlistError = HTTPValidationError;

export type TriggerAccountCreatedForAllResponse = unknown;

export type TriggerAccountCreatedForAllError = unknown;

export type BaserowWebhookResponse = unknown;

export type BaserowWebhookError = unknown;

export type UpdateEmptyNamesInBaserowResponse = unknown;

export type UpdateEmptyNamesInBaserowError = unknown;

export type RemoveDuplicateRowsResponse = unknown;

export type RemoveDuplicateRowsError = unknown;

export type ProcessInstagramUrlData = {
  body: InstagramURLRequest;
};

export type ProcessInstagramUrlResponse = unknown;

export type ProcessInstagramUrlError = HTTPValidationError;

export type UploadImageData = {
  body: Body_home_design_projects_upload_image;
};

export type UploadImageResponse = ImageUploadResponse;

export type UploadImageError = HTTPValidationError;

export type CreateProjectData = {
  body: HomeDesignProjectCreate;
};

export type CreateProjectResponse = HomeDesignProjectRead;

export type CreateProjectError = ErrorResponse | HTTPValidationError;

export type GetUserProjectsData = {
  query?: {
    limit?: number;
    skip?: number;
  };
};

export type GetUserProjectsResponse = Array<HomeDesignProjectRead>;

export type GetUserProjectsError = HTTPValidationError;

export type GetProjectData = {
  path: {
    project_id: string;
  };
};

export type GetProjectResponse = HomeDesignProjectRead;

export type GetProjectError = HTTPValidationError;

export type UpdateProjectData = {
  body: HomeDesignProjectUpdate;
  path: {
    project_id: string;
  };
};

export type UpdateProjectResponse = HomeDesignProjectRead;

export type UpdateProjectError = HTTPValidationError;

export type DeleteProjectData = {
  path: {
    project_id: string;
  };
};

export type DeleteProjectResponse = unknown;

export type DeleteProjectError = HTTPValidationError;

export type ChatWithClaudeData = {
  body: HomeDesignChatRequest;
};

export type ChatWithClaudeResponse = HomeDesignChatResponse;

export type ChatWithClaudeError = ErrorResponse | HTTPValidationError;

export type GetProjectConversationsData = {
  path: {
    project_id: string;
  };
};

export type GetProjectConversationsResponse = Array<HomeDesignConversationRead>;

export type GetProjectConversationsError = HTTPValidationError;

export type GetProjectEditsData = {
  path: {
    project_id: string;
  };
};

export type GetProjectEditsResponse = Array<HomeDesignEditRead>;

export type GetProjectEditsError = HTTPValidationError;
